# Generated by Django 5.1.15 on 2026-06-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='document_type',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('repair_cost_estimate', 'Repair Cost Estimate')], default='quotation', max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='expected_completion_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='warranty_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
