# Generated by Django 5.1.15 on 2026-06-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_quotation_document_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='expected_completion_days',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='warranty_months',
        ),
    ]
