# Generated by Django 5.1.15 on 2026-06-15 04:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('quotations', '0001_initial'),
        ('tenants', '0002_companyentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('report_date', models.DateField(default=django.utils.timezone.localdate)),
                ('customer_lpo', models.CharField(blank=True, max_length=100)),
                ('drn', models.CharField(blank=True, max_length=100)),
                ('attention_person', models.CharField(blank=True, max_length=150)),
                ('equipment_details', models.TextField(blank=True)),
                ('work_description', models.TextField(blank=True)),
                ('site_location', models.CharField(blank=True, max_length=255)),
                ('equipment_id', models.CharField(blank=True, max_length=100)),
                ('work_start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('quotation_reference', models.CharField(blank=True, max_length=100)),
                ('recommendations', models.TextField(blank=True)),
                ('job_status', models.CharField(choices=[('operational', 'Operational'), ('under_observation', 'Under Observation'), ('needs_followup', 'Needs Follow-up')], default='operational', max_length=30)),
                ('technician_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('sent', 'Sent'), ('invoiced', 'Invoiced'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reports_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_reports', to='customers.customer')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_reports', to='tenants.companyentity')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reports', to='quotations.quotation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='service_rep_tenant__89230c_idx'), models.Index(fields=['tenant', 'reference_number'], name='service_rep_tenant__1e2820_idx')],
            },
        ),
    ]
