# Generated by Django 5.1.15 on 2026-06-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='condition_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='customer_representative',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='pump_kw',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='subject',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='tank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='test_results',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='warranty_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
