# Generated by Django 5.1.15 on 2026-06-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_reports', '0002_servicereport_condition_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereport',
            name='condition_notes',
        ),
        migrations.RemoveField(
            model_name='servicereport',
            name='customer_representative',
        ),
        migrations.RemoveField(
            model_name='servicereport',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='servicereport',
            name='pump_kw',
        ),
        migrations.RemoveField(
            model_name='servicereport',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='servicereport',
            name='supervisor_name',
        ),
        migrations.RemoveField(
            model_name='servicereport',
            name='tank_name',
        ),
        migrations.RemoveField(
            model_name='servicereport',
            name='test_results',
        ),
        migrations.RemoveField(
            model_name='servicereport',
            name='warranty_months',
        ),
    ]
