# Generated by Django 5.1.15 on 2026-06-15 04:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('tenants', '0002_companyentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.PositiveIntegerField()),
                ('previous_invoice_number', models.PositiveIntegerField(blank=True, null=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('customer_lpo', models.CharField(blank=True, max_length=100)),
                ('drn', models.CharField(blank=True, max_length=100, verbose_name='Delivery Reference Number')),
                ('quotation_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('sent', 'Sent'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('credited', 'Credited')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('net_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.05'), max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payment_terms_days', models.PositiveIntegerField(default=30)),
                ('payment_terms_text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('retention_rate', models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=5)),
                ('retention_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('late_fee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.03'), max_digits=5)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('exceed_days', models.IntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tenants.companyentity')),
            ],
            options={
                'ordering': ['-invoice_date', '-invoice_number'],
            },
        ),
    ]
