# Generated by Django 5.1.15 on 2026-06-15 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit_notes', '0001_initial'),
        ('invoices', '0001_initial'),
        ('tenants', '0002_companyentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='original_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='creditnotelineitem',
            name='credit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='credit_notes.creditnote'),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.UniqueConstraint(fields=('tenant', 'entity', 'credit_note_number'), name='unique_tenant_entity_credit_note_number'),
        ),
    ]
