# Generated by Django 5.1.15 on 2026-06-21 14:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('service_reports', '0002_servicereport_condition_notes_and_more'),
        ('tenants', '0004_companyentity_evaluation_prefix_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyCertificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('certificate_date', models.DateField(default=django.utils.timezone.localdate)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('attention_person', models.CharField(blank=True, max_length=150)),
                ('drn', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, default='1', max_length=50)),
                ('pump_kw', models.CharField(blank=True, max_length=50)),
                ('pump_no', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('tank_name', models.CharField(blank=True, max_length=255)),
                ('finishing_date', models.DateField(blank=True, null=True)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('customer_lpo', models.CharField(blank=True, max_length=100)),
                ('service_report_reference', models.CharField(blank=True, max_length=100)),
                ('work_description', models.TextField(blank=True)),
                ('warranty_months', models.PositiveIntegerField(default=6)),
                ('warranty_statement', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_certificates_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_certificates', to='customers.customer')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_certificates', to='tenants.companyentity')),
                ('service_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_certificates', to='service_reports.servicereport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-certificate_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='warranty_ce_tenant__741982_idx'), models.Index(fields=['tenant', 'reference_number'], name='warranty_ce_tenant__5b7ff1_idx')],
            },
        ),
    ]
