# Generated by Django 5.1.15 on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warranty_certificates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warrantycertificate",
            name="work_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="warrantycertificate",
            name="signatory_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="warrantycertificate",
            name="signatory_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="warrantycertificate",
            name="signatory_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
