# Generated by Django 5.1.15 on 2026-06-22

import uuid

import django.db.models.deletion
from django.db import migrations, models


def migrate_legacy_equipment_fields(apps, schema_editor):
    WarrantyCertificate = apps.get_model("warranty_certificates", "WarrantyCertificate")
    WarrantyCertificateItem = apps.get_model("warranty_certificates", "WarrantyCertificateItem")

    for certificate in WarrantyCertificate.objects.all():
        has_legacy = any([
            certificate.pump_kw,
            certificate.pump_no,
            certificate.location,
            certificate.tank_name,
            certificate.serial_number,
        ])
        if not has_legacy:
            continue

        serial = 1
        if str(certificate.serial_number).isdigit():
            serial = int(certificate.serial_number)

        product_name = certificate.work_title or certificate.pump_kw or "Equipment"
        WarrantyCertificateItem.objects.create(
            id=uuid.uuid4(),
            certificate_id=certificate.id,
            serial_number=serial,
            product_name=product_name[:255],
            specification=(certificate.pump_kw or "")[:255],
            identifier=(certificate.pump_no or "")[:100],
            location=(certificate.location or "")[:255],
            site_reference=(certificate.tank_name or "")[:255],
        )


class Migration(migrations.Migration):

    dependencies = [
        ("warranty_certificates", "0002_warrantycertificate_signatory_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarrantyCertificateItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("serial_number", models.PositiveIntegerField(default=1)),
                ("product_name", models.CharField(max_length=255)),
                ("specification", models.CharField(blank=True, max_length=255)),
                ("identifier", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("site_reference", models.CharField(blank=True, max_length=255)),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="warranty_certificates.warrantycertificate",
                    ),
                ),
            ],
            options={
                "ordering": ["serial_number", "created_at"],
            },
        ),
        migrations.RunPython(migrate_legacy_equipment_fields, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="warrantycertificate",
            name="location",
        ),
        migrations.RemoveField(
            model_name="warrantycertificate",
            name="pump_kw",
        ),
        migrations.RemoveField(
            model_name="warrantycertificate",
            name="pump_no",
        ),
        migrations.RemoveField(
            model_name="warrantycertificate",
            name="serial_number",
        ),
        migrations.RemoveField(
            model_name="warrantycertificate",
            name="tank_name",
        ),
    ]
