# Generated by Django 5.1.15 on 2026-06-15 04:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('trn', models.CharField(blank=True, max_length=50, verbose_name='Tax Registration Number')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, default='Abu Dhabi', max_length=100)),
                ('country', models.CharField(blank=True, default='UAE', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='trial', max_length=20)),
                ('default_vat_rate', models.DecimalField(decimal_places=4, default=0.05, max_digits=5)),
                ('default_payment_terms_days', models.PositiveIntegerField(default=30)),
                ('default_retention_rate', models.DecimalField(decimal_places=4, default=0.1, max_digits=5)),
                ('default_late_fee_rate', models.DecimalField(decimal_places=4, default=0.03, max_digits=5)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
    ]
