# Generated by Django 5.1.15 on 2026-06-15 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEntity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('trn', models.CharField(blank=True, max_length=50, verbose_name='Tax Registration Number')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, default='Abu Dhabi', max_length=100)),
                ('country', models.CharField(blank=True, default='UAE', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entities/logos/')),
                ('is_default', models.BooleanField(default=False)),
                ('quotation_prefix', models.CharField(blank=True, default='QTN', max_length=20)),
                ('invoice_prefix', models.CharField(blank=True, default='INV', max_length=20)),
                ('credit_note_prefix', models.CharField(blank=True, default='CN', max_length=20)),
                ('service_report_prefix', models.CharField(blank=True, default='SR', max_length=20)),
                ('next_invoice_number', models.PositiveIntegerField(default=1)),
                ('next_quotation_number', models.PositiveIntegerField(default=1)),
                ('next_credit_note_number', models.PositiveIntegerField(default=1)),
                ('next_service_report_number', models.PositiveIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Company Entity',
                'verbose_name_plural': 'Company Entities',
                'ordering': ['name'],
            },
        ),
    ]
