# Generated by Django 5.1.15 on 2026-06-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_companyentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_payment_terms_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_terms_and_conditions',
            field=models.TextField(blank=True),
        ),
    ]
