# Generated by Django 5.1.15 on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_remove_companyentity_evaluation_prefix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyentity",
            name="warranty_prefix",
            field=models.CharField(blank=True, default="WC", max_length=20),
        ),
        migrations.AddField(
            model_name="companyentity",
            name="next_warranty_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
